### ISSUE TITLE
Use AppCompat views

### ISSUE THREAD

**Issue by danielsanfr** [elye/loaderviewlibrary#10]
First your library is cool and simply do what it promises.

As mentioned in the documentation, it is interesting that your implementations extends [AppCompatImageView](https://developer.android.com/reference/android/support/v7/widget/AppCompatImageView.html) and [AppCompatTextView](https://developer.android.com/reference/android/support/v7/widget/AppCompatTextView.html).

Sorry my poor English :(.

**Comment by elye** [comment]
Hi @danielsanfr . 
Thanks for your input. Sorry, I didn't really understand your message. If you need to support older version of Android, perhaps you could try to make a PR as per your need, so I could fully understand your request.
Regards,
