### ISSUE TITLE
Use case in recyclerview

### ISSUE THREAD

**Issue by ClaudeHangui** [elye/loaderviewlibrary#14]
How does it work inside an adapter class?? 
Use case: I already have a dataset in my listview/recyclerview and I make a swipetorefresh list..
how do I notify the viewholder to start the loading animation while awaiting data from the network ?

**Comment by kobusLink** [comment]
Is it not be possible to call the View.resetLoader(); method from your activity?

**Comment by kobusLink** [comment]
Is it not possible to use the View.resetLoader(); method inside the adapter class?

**Comment by elye** [comment]
@kobusLink noted that very well. Thanks. 
@ClaudeHangui, when you swipe to refresh, if there's no data, you shouldn't be displaying the recyclerview list of empty data. Ideally from a design point of view, an empty state view should be shown. Hope this helps.

I'm closing this issue unless there's further inquiries. Thanks.
