### ISSUE TITLE
Support of custom views

### ISSUE THREAD

**Issue by bartoszostrowski** [elye/loaderviewlibrary#15]
I am trying to use LoaderViewLibrary in conjunction with custom TextViews and ImageViews, but encontered some issue - LoaderView interface accessibility (LoaderViewLibrary included via Gradle)

Do you have some experience with supporting custom views without need of "re-implementing" them?

Have you considered using LoaderView as layout encapsulating inner views? Similar to e.g.: https://github.com/traex/RippleEffect

**Comment by elye** [comment]
Hi @bartoszostrowski , you still can use ripple effect, just add this view into the a layout container, and had the layout had the [ripple drawable](https://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html) as the background color of the layout container.

You could check this out as well on how to implement ripple.
https://stackoverflow.com/questions/27006288/how-to-create-ripple-effect-in-simple-layout

If you want to custom the view, you could do so by extending from `LoaderTextView` or `LoaderImageView`, then write your custom function there. These classes are open, so you could extend from them.

I'm closing this issue, unless you have further issue.
