### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zhangzhichaolove** [elye/loaderviewlibrary#16]
Source code：
        valueAnimator.cancel();
        setValueAnimator(progress, 0, 0);
        valueAnimator.start();
After execution, the animation has been running and has not stopped, causing memory to continue to grow，Debug The onAnimationUpdate monitor is being implemented.

**Comment by zhangzhichaolove** [comment]
Recycler Item How do I solve this problem when reusing?

**Comment by elye** [comment]
Hi @zhangzhichaolove, do note that `setValueAnimator(progress, 0, 0);` is setting the valueAnimator to perform the last round of animation before finish. Hence it will only last 0.75 second. So the memory leak shouldn't happen.

As for using it in recyclerView, in your view holder, whenever you bind the view, you could call `resetLoader()` whenever you have a new view. But I suspect if you would to use RecyclerView, your data would have be in place, and the need of waiting to load the data everytime the viewholder is invalidated would not be needed.

I am closing this issue, unless you have further inquiry and evidence of leaks. Thanks.
