### ISSUE TITLE
Error:(5, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

### ISSUE THREAD

**Issue by suman-tms** [elye/loaderviewlibrary#2]
I am having problem to build the project after adding dependency to the build.gradle file. 

<img width="1176" alt="screen shot 2016-09-01 at 9 22 27 am" src="https://cloud.githubusercontent.com/assets/10903786/18154596/aab7eeae-7025-11e6-8318-56e1b4c307dc.png">

**Comment by elye** [comment]
Could this be related to http://stackoverflow.com/questions/35628572/update-support-library-23-2-0-build-bug? My library didn't use this resource explicitly. Perhaps your code is using it, and the upgrade of library cause some issue?

**Comment by elye** [comment]
I assume this solve your issue. So I'm closing this issue. You could reopen if the issue persist. Thanks.
