### ISSUE TITLE
LoaderImageView leaks memory

### ISSUE THREAD

**Issue by passiondroid** [elye/loaderviewlibrary#21]
LoaderImageView leaks memory as it holds the context of the activity.
Please check the below screenshot from Leakcanary

![image](https://user-images.githubusercontent.com/1834030/33830232-5488be8a-de99-11e7-85bb-7efae25489e0.png)

**Comment by elye** [comment]
It is unlikely LoaderImageView itself leaks. The mContext passed to it, is like any context pass to ImageView. LoaderImageView itself doesn't use the mContext, but the ImageView (which it inherits does). In normal case, the LoaderImageView (ImageView) would be destroy when HomeActivity is destroy. 

The only possible exception is you have load some drawable object to the ImageView, here the object lives longer than HomeActivity. Hence this preventing ImageView (or LoaderImageView) from being destroy when HomeActivity is destroyed. And with that, the mContext it holds leaks.

Check out this blog post http://www.curious-creature.com/2008/12/18/avoid-memory-leaks-on-android/ by Roman Guy.
