### ISSUE TITLE
Width Weight not support RTL

### ISSUE THREAD

**Issue by salahamassi** [elye/loaderviewlibrary#23]
I am Trying to fix this issue by check Language if its RTL and then draw round rect in reverse.

Is there a better solution?

<img width="919" alt="screen shot 2018-03-02 at 5 52 54 pm" src="https://user-images.githubusercontent.com/17902030/36907964-a3e312bc-1e42-11e8-94dc-b7947091418c.png">

**Comment by elye** [comment]
Do post your question in https://stackoverflow.com/. I believe someone would be able to help you from there.
