### ISSUE TITLE
运行直接找不到这个类

### ISSUE THREAD

**Issue by s3hengwu** [elye/loaderviewlibrary#3]
android.view.InflateException: Binary XML file line #39: Error inflating class <unknown>

**Comment by elye** [comment]
Hi s3hengwu,

From the error message, I suspect you have not manage to include the library into your project by adding the following line into your gradle.build.

`dependencies {
    compile 'com.elyeproj.libraries:loaderviewlibrary:1.1.0'
}`

Can you check? Thanks.

**Comment by elye** [comment]
I assume this solve your issue. So I'm closing this issue. You could reopen if the issue persist. Thanks.
