### ISSUE TITLE
Is there a way that i can show shimmer for a spasific amount of time

### ISSUE THREAD

**Issue by VyshnavVK** [elye/loaderviewlibrary#32]
i don't have much data to load so before shimmer can be displayed data loads if possible add a time delay before data set to imageView and TextView

**Comment by MahmoudMabrok** [comment]
u can use `Handler().postdelayed`

**Comment by VyshnavVK** [comment]
it's it a lazy way of donig it ?

**Comment by elye** [comment]
This should be the logic you can code on your end and decide what to be shown. You have all the control.
