### ISSUE TITLE
decoupling setText and revealing the content

### ISSUE THREAD

**Issue by pellyadolfo** [elye/loaderviewlibrary#4]
I like the library. I would like to suggest a new functionality. My UI components are built dynamically so I know how many they are only on setText(). The problem is that the loader is never shown.

I think would be interesting decoupling the revealContent() action from the setText() so, even after the text is already in place after calling setText(), the text is not really shown until you run a revealContent() action.

Does this make sense?

**Comment by pellyadolfo** [comment]
Probably not the cleanest way to solve this but I did a kind of patch that works for me. I added a memory of the text to be set. 

```
// delay set text
public String textValue = null;
public void storeValue (String value) {
    textValue = value;
}
public void revealValue() {
    if (textValue != null)
            setText(textValue);
}
```

It would be better to have the opacity hiding the text already in place, but I could not find the way in a short time so I opted for this fix.

Thanks for the library.

**Comment by elye** [comment]
Hi Pellyadolfo,

Thanks for your interest in this library.  

I understand you have some special requirements. However there's some challenges if we change the behavior of setText() to not display by default as below.
1.) setText() for the original TextView will display the text.
2.) the existing library behavior is already having setText() to display the view.

Nevertheless, you could have the option of override the class by extending the LoaderTextView by changing the behavior of setText() to call your propose storeValue() function above, and having the the revealValue() then only call super.setText() as you show above. 

With that, you could have your behavior intended while getting the benefit of loader shimmer animation as you like, and doesn't impact other user who already uses this library. 

Hope this suggestion helps.

**Comment by elye** [comment]
Closing this, given this is not an issue. It is specific enhancement request that could be done by overriding the class.
