### ISSUE TITLE
Enable loading view again with setText(null),

### ISSUE THREAD

**Issue by KhaledLela** [elye/loaderviewlibrary#9]
Thanks for your great library,
But i want to know how can i enable loading view after `setText()` method called,
When use `LoaderTextView` inside `RecyclerView` adapter and when refreshing the adapter and waiting for server response it will be great to enabled loading view again **without re-inflating** visible items,

**Comment by elye** [comment]
Good input. Thanks. I might consider enhancing this when time permits. If you want to submit a pull request to enhance the library, most welcome. Thanks.

**Comment by elye** [comment]
Added this feature in v1.2.0
